[variables]
PORT = "8000"
HOST = "0.0.0.0"
ENVIRONMENT = "production"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y curl libmagic-dev poppler-utils tesseract-ocr tesseract-ocr-spa libreoffice pandoc qpdf",
    "apt-get clean",
    "rm -rf /var/lib/apt/lists/*"
]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm ci && npm run build"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[staticAssets]
"frontend/dist" = "/"